//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/MsgPrepared.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPrepared")]
  public partial class MsgPrepared : global::ProtoBuf.IExtensible
  {
    public MsgPrepared() {}
    
    private int _currentNum;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"currentNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int currentNum
    {
      get { return _currentNum; }
      set { _currentNum = value; }
    }
    private int _maxNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxNum
    {
      get { return _maxNum; }
      set { _maxNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}