//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/MsgGeneratePrefab.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGeneratePrefab")]
  public partial class MsgGeneratePrefab : global::ProtoBuf.IExtensible
  {
    public MsgGeneratePrefab() {}
    
    private string _prefabName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"prefabName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prefabName
    {
      get { return _prefabName; }
      set { _prefabName = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private float _eulerX = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"eulerX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float eulerX
    {
      get { return _eulerX; }
      set { _eulerX = value; }
    }
    private float _eulerY = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"eulerY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float eulerY
    {
      get { return _eulerY; }
      set { _eulerY = value; }
    }
    private float _eulerZ = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"eulerZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float eulerZ
    {
      get { return _eulerZ; }
      set { _eulerZ = value; }
    }
    private float _durTime = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"durTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float durTime
    {
      get { return _durTime; }
      set { _durTime = value; }
    }
    private bool _isFllowTarget = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isFllowTarget", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isFllowTarget
    {
      get { return _isFllowTarget; }
      set { _isFllowTarget = value; }
    }
    private string _targetId = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGeneratePrefabWDis")]
  public partial class MsgGeneratePrefabWDis : global::ProtoBuf.IExtensible
  {
    public MsgGeneratePrefabWDis() {}
    
    private string _prefabName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"prefabName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string prefabName
    {
      get { return _prefabName; }
      set { _prefabName = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private float _eulerX = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"eulerX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float eulerX
    {
      get { return _eulerX; }
      set { _eulerX = value; }
    }
    private float _eulerY = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"eulerY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float eulerY
    {
      get { return _eulerY; }
      set { _eulerY = value; }
    }
    private float _eulerZ = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"eulerZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float eulerZ
    {
      get { return _eulerZ; }
      set { _eulerZ = value; }
    }
    private float _moveSpeed = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"moveSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float moveSpeed
    {
      get { return _moveSpeed; }
      set { _moveSpeed = value; }
    }
    private float _targetX = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"targetX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float targetX
    {
      get { return _targetX; }
      set { _targetX = value; }
    }
    private float _targetY = default(float);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"targetY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float targetY
    {
      get { return _targetY; }
      set { _targetY = value; }
    }
    private float _targetZ = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"targetZ", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float targetZ
    {
      get { return _targetZ; }
      set { _targetZ = value; }
    }
    private float _durTime = default(float);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"durTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float durTime
    {
      get { return _durTime; }
      set { _durTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}