//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/MsgHit.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgHit")]
  public partial class MsgHit : global::ProtoBuf.IExtensible
  {
    public MsgHit() {}
    
    private string _targetId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string targetId
    {
      get { return _targetId; }
      set { _targetId = value; }
    }
    private string _attackId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"attackId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string attackId
    {
      get { return _attackId; }
      set { _attackId = value; }
    }
    private float _hitNum = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hitNum", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float hitNum
    {
      get { return _hitNum; }
      set { _hitNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}