//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/MsgResult.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgDeath")]
  public partial class MsgDeath : global::ProtoBuf.IExtensible
  {
    public MsgDeath() {}
    
    private string _deathID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"deathID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deathID
    {
      get { return _deathID; }
      set { _deathID = value; }
    }
    private int _belongCamp = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"belongCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int belongCamp
    {
      get { return _belongCamp; }
      set { _belongCamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgBattleResult")]
  public partial class MsgBattleResult : global::ProtoBuf.IExtensible
  {
    public MsgBattleResult() {}
    
    private int _winCamp = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"winCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winCamp
    {
      get { return _winCamp; }
      set { _winCamp = value; }
    }
    private int _loseCamp = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"loseCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int loseCamp
    {
      get { return _loseCamp; }
      set { _loseCamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}